# Generated by Django 6.0.6 on 2026-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cover', '0002_contact_product_suggestion_delete_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
